상품관리 리뷰 후 승인 부탁드립니다.
nhn-on7/marketgg-client pull request #58
Opened 2022-07-15 05:30 UTC by Com-Sun

## 개요
- 상품 CRUD 기능 구현
- 상품 생성, 수정 시 Toast Editor 연동
- 서버 - 클라이언트 통신을 통해 받은 데이터를 타임리프를 사용하여 표시

## 작업사항

### index 페이지
<img width="600" alt="스크린샷 2022-07-15 오후 2 22 45" src="https://user-images.githubusercontent.com/78946348/179156282-b7d1c97a-aafa-46b4-98d9-58b2b9642379.png">

### Create
<img width="1430" alt="스크린샷 2022-07-15 오후 2 20 14" src="https://user-images.githubusercontent.com/78946348/179156051-5a301643-7b2f-4ea4-972c-78abc82c661d.png">

### Read

- 상품 전체 조회
<img width="596" alt="스크린샷 2022-07-15 오후 2 24 24" src="https://user-images.githubusercontent.com/78946348/179156469-c02d8326-6081-4ad2-8639-1bda82a81b6b.png">

- 상품 상세 조회
<img width="1397" alt="스크린샷 2022-07-15 오후 2 25 09" src="https://user-images.githubusercontent.com/78946348/179156719-93e0cfa9-228e-4035-8b7a-f4a2e60ed505.png">

- 카테고리로 상품 조회
- #56 

### Update
- #52 

### Delete
- 소프트 삭제로 구현

## 기타사항
- JavaDoc 작성해야합니다
- Test Code 작성해야합니다.

2022-07-15 06:00 UTC, psw4887 commented on src/main/java/com/nhnacademy/marketgg/client/config/WebConfiguration.java
>          return "http://localhost:6060";
merge 하실 때 하드코딩 되어있던 부분 develop 브랜치의 yml으로 관리될 예정입니다.

2022-07-15 06:00 UTC, psw4887 commented on src/main/java/com/nhnacademy/marketgg/client/repository/impl/ProductAdapter.java
> +        // TODO: Log를 AOP로 뺴기
Log 를 Aop로 뺀다기 보단 현재 상황으로는 Aop 로 Adapter의 메소드가 실행될 때 해당 메소드가 실행됐는지 체크 정도만 하고 Uri를 Aop에 가져와 로그를 찍는 상황은 아닙니다. 참고 바랍니다.

2022-07-15 06:00 UTC, psw4887 commented on src/main/java/com/nhnacademy/marketgg/client/repository/impl/ProductAdapter.java
> +
메소드 선언이 한줄 인 경우 개행을 하지 않기로 했습니다. 이하 같은 리뷰는 생략하겠습니다.
없애주시면 더 좋을 것 같아요.

2022-07-15 06:00 UTC, psw4887 commented on src/main/java/com/nhnacademy/marketgg/client/repository/impl/ProductAdapter.java
> +        HttpEntity<byte[]> doc = new HttpEntity<>(image.getBytes(), headerMap);
doc라는 변수명을 사용하셨는데 혹시 어떤 목적인지 알 수 있을까요? 
doc만 봐서는 무엇인지 잘 모르겠습니다.

2022-07-15 06:00 UTC, psw4887 commented on src/main/java/com/nhnacademy/marketgg/client/repository/impl/ProductAdapter.java
> +        HttpEntity<Void> httpEntity = new HttpEntity<>(headers);
해당 HttpEntity가 요청 엔티티라면 앞에 request같은 의미를 붙여주시면 더 표현력이 좋을 것 같습니다.

2022-07-15 06:00 UTC, psw4887 commented on src/main/java/com/nhnacademy/marketgg/client/repository/impl/ProductAdapter.java
> +        log.info(String.valueOf(response.getHeaders().getLocation()));
매 RestTemplate 마다 응답 헤더의 Location 을 찍는 과정이 반복되고있는데 하나의 메소드로 분류해서 관리하면 더 좋은 코드가 될 것 같습니다.

2022-07-15 06:00 UTC, psw4887 commented on src/main/java/com/nhnacademy/marketgg/client/service/impl/DefaultProductService.java
> +        productRepository.updateProduct(productId, image, productRequest);
개행이 빠져있습니다. 추가 부탁드립니다.

2022-07-15 06:00 UTC, psw4887 commented on src/main/java/com/nhnacademy/marketgg/client/web/ProductController.java
> +    public ModelAndView updateProduct(@RequestPart(value = "image") final MultipartFile image,
@PathVariable 파라미터가 가장 먼저 위치해있기로 코드 스타일을 정한 것 같습니다.
수정해주시면 더 좋은 코드가 될 것 같습니다. 이하 같은 내용의 리뷰는 생략하도록 하겠습니다.

2022-07-15 06:00 UTC, psw4887 commented on src/main/resources/static/js/toast.js
> +})
모든 파일이 끝날 때 추가 개행을 해주기로 코드 스타일을 적용하기로 한걸로 알고 있습니다.
개행 부탁드립니다. 이하 같은 리뷰는 생략하도록  하겠습니다.

2022-07-15 06:03 UTC, Jungmin-Kim228 requested changes

2022-07-15 06:03 UTC, Jungmin-Kim228 commented on src/main/resources/templates/index.html
> +</html>
마지막 줄 개행이 없어 파일 끝을 인식하지 못하고 있습니다.

이하 같은 사항
- 모든 html 파일

2022-07-15 06:03 UTC, Jungmin-Kim228 commented on src/main/java/com/nhnacademy/marketgg/client/web/ProductController.java
> +    public ModelAndView retrieveProductDetails(@PathVariable Long productId) {
final 을 깜빡하신 것 같습니다.

이하 같은 사항
- ProductController 내부에 더 있습니다.
- DefaultProductService
- ProductService
- ProductAdapter
- ProductRepository

2022-07-15 06:07 UTC, Jungmin-Kim228 commented on src/main/java/com/nhnacademy/marketgg/client/web/ProductController.java
> +    @PostMapping("/{productId}/deleted")
다른 경로들은 update, search 등으로 되어있는데 이곳만 deleted 인 이유가 있나요?

2022-07-15 08:18 UTC, nhn-academy-marco reviewed
고생하셨습니다.^^

2022-07-15 08:18 UTC, nhn-academy-marco commented on src/main/java/com/nhnacademy/marketgg/client/repository/impl/ProductAdapter.java
> +        multipartReqMap.add("image", doc);
multipartReqMap 이미지를 담아서 처리하는 과정이 생성, 수정 ... 
중복코드가 발생하는거 같아요 method 분리 해보는건 어떨까요?

2022-07-15 08:18 UTC, nhn-academy-marco commented on src/main/resources/templates/products/product-form.html
> +        <form name="form" method="post" action="/admin/v1/products/create" enctype="multipart/form-data">
csrf 적용해주세요~

2022-07-15 08:18 UTC, nhn-academy-marco commented on src/main/java/com/nhnacademy/marketgg/client/web/ProductController.java
> +        ModelAndView mav = new ModelAndView("products/product-modify-form");
products/product-modify-form 과 products/product-form 
공동으로 사용할 방법을 생각해보세요. 분리를 하게되면 ui는 동일하지만 수정은 양쪽다 해야되는 상황이 발생할거 같아요.

2022-07-15 08:18 UTC, nhn-academy-marco commented on src/main/resources/templates/products/retrieve-products.html
> +                        th:onclick="'location.href=\''+ @{|/admin/v1/products/${product.productNo}|} + '\''" style="color: tomato">업무 이름
"'location.href=\''+ @{|/admin/v1/products/${product.productNo}|} + '\''" 어떤 의미인가요?
업무이름을 클릭 했을 대 이벤트가 발생 하도록 javascript - > .js 쪽에서 처리해 보면 어떨가요?

2022-07-15 08:18 UTC, nhn-academy-marco commented on src/main/resources/templates/products/retrieve-products.html
> +                        th:onclick="'location.href=\''+ @{|/admin/v1/products/update/${product.productNo}|} + '\''" style="color: dodgerblue">상품 수정
.js <-- 이벤트 처리해보면 어떨까요?

2022-07-15 08:18 UTC, nhn-academy-marco commented on src/main/resources/templates/products/index.html
> +<!doctype html>
thymeleaf layout 이용해서 전체적으로 화면 구조를 다시 잡아보세요
https://github.com/ultraq/thymeleaf-layout-dialect

2022-07-15 08:22 UTC, nhn-academy-marco commented on src/main/java/com/nhnacademy/marketgg/client/web/ProductController.java
> +        List<ProductResponse> products = productService.retrieveProducts();
ui쪽 페이징 처리가 안된거 같네요. api 쪽 확인하셔서 ui에서 페이징 처리가 가능할 수 있도록 responseDto 변경해보세요.

2022-07-15 08:22 UTC, nhn-academy-marco reviewed
페이징 처리

2022-07-15 08:56 UTC, Jungmin-Kim228 approved these changes

2022-07-15 08:56 UTC, corock commented on src/main/java/com/nhnacademy/marketgg/client/config/WebConfiguration.java
>          return "http://localhost:6060";
팀 내에서 `gist` 로 설정 파일 공유하여 관리하겠습니다.

2022-07-15 08:57 UTC, corock approved these changes

2022-07-15 09:07 UTC, merged

2022-07-16 13:15 UTC, Com-Sun reviewed
마르코 교수님 지적사항 마저 수정한 뒤에 resolve 처리 할 예정

2022-07-16 13:15 UTC, Com-Sun commented on src/main/java/com/nhnacademy/marketgg/client/web/ProductController.java
> +    public ModelAndView retrieveProductDetails(@PathVariable Long productId) {
final 같은 컨벤션 부분은 리뷰 지적받은 부분을 다 수정한 뒤에 한 번에 수정하도록 하겠습니다.

2022-07-16 13:15 UTC, Com-Sun commented on src/main/java/com/nhnacademy/marketgg/client/web/ProductController.java
> +        ModelAndView mav = new ModelAndView("products/product-modify-form");
해당 부분 TODO로 기록하겠습니다. 감사합니다.

2022-07-16 13:15 UTC, Com-Sun commented on src/main/java/com/nhnacademy/marketgg/client/web/ProductController.java
> +    public ModelAndView updateProduct(@RequestPart(value = "image") final MultipartFile image,
수정하였습니다. 
다른 부분도 확인하는대로 수정하겠습니다. 감사합니다.

2022-07-16 13:15 UTC, Com-Sun commented on src/main/java/com/nhnacademy/marketgg/client/web/ProductController.java
> +    @PostMapping("/{productId}/deleted")
듣고 보니 그렇네요.
해당 부분 delete로 수정하였습니다.

2022-07-16 13:15 UTC, Com-Sun commented on src/main/resources/static/js/toast.js
> +})
해당부분 수정하였습니다.

2022-07-16 13:15 UTC, Com-Sun commented on src/main/resources/templates/index.html
> +</html>
해당 부분 수정하였습니다.

2022-07-16 13:15 UTC, Com-Sun commented on src/main/resources/templates/products/index.html
> +<!doctype html>
감사합니다. 링크 참고하여 수정하겠습니다.

2022-07-16 13:15 UTC, Com-Sun commented on src/main/resources/templates/products/retrieve-products.html
> +                        th:onclick="'location.href=\''+ @{|/admin/v1/products/${product.productNo}|} + '\''" style="color: tomato">업무 이름
조언 감사합니다. 해당 부분 JS로 바꿔보겠습니다.

2022-07-16 13:15 UTC, Com-Sun commented on src/main/resources/templates/products/retrieve-products.html
> +                        th:onclick="'location.href=\''+ @{|/admin/v1/products/update/${product.productNo}|} + '\''" style="color: dodgerblue">상품 수정
감사합니다. 해당 부분 JS로 바꿔보겠습니다.

2022-07-16 20:03 UTC, coalong commented on src/main/java/com/nhnacademy/marketgg/client/repository/impl/ProductAdapter.java
> +        HttpEntity<byte[]> doc = new HttpEntity<>(image.getBytes(), headerMap);
변수명을 명시적으로 나타낼 수 있게 수정했습니다.

2022-07-16 20:04 UTC, coalong commented on src/main/java/com/nhnacademy/marketgg/client/domain/dto/request/ProductCreateRequest.java
> +@AllArgsConstructor
Request DTO 어노테이션을 @RequiredArgsConstructor 로 수정했습니다.